# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created: Mon Jun 06 15:44:55 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore
from PySide import QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 572)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 80))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.dadosButton = QtGui.QToolButton(self.frame)
        self.dadosButton.setGeometry(QtCore.QRect(10, 0, 190, 80))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(12)
        self.dadosButton.setFont(font)
        self.dadosButton.setAutoExclusive(True)
        self.dadosButton.setObjectName("dadosButton")
        self.classificacaoButton = QtGui.QToolButton(self.frame)
        self.classificacaoButton.setGeometry(QtCore.QRect(206, 0, 190, 80))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(12)
        self.classificacaoButton.setFont(font)
        self.classificacaoButton.setAutoExclusive(True)
        self.classificacaoButton.setObjectName("classificacaoButton")
        self.entrada2Button = QtGui.QToolButton(self.frame)
        self.entrada2Button.setGeometry(QtCore.QRect(403, 0, 190, 80))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(12)
        self.entrada2Button.setFont(font)
        self.entrada2Button.setAutoExclusive(True)
        self.entrada2Button.setObjectName("entrada2Button")
        self.resultado2Button = QtGui.QToolButton(self.frame)
        self.resultado2Button.setGeometry(QtCore.QRect(600, 0, 190, 80))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(12)
        self.resultado2Button.setFont(font)
        self.resultado2Button.setAutoExclusive(True)
        self.resultado2Button.setObjectName("resultado2Button")
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 90, 801, 491))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.abrirButton = QtGui.QPushButton(self.page_4)
        self.abrirButton.setGeometry(QtCore.QRect(20, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(12)
        self.abrirButton.setFont(font)
        self.abrirButton.setObjectName("abrirButton")
        self.groupBox_2 = QtGui.QGroupBox(self.page_4)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 170, 381, 291))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.tabelaAtributos = QtGui.QTableWidget(self.groupBox_2)
        self.tabelaAtributos.setGeometry(QtCore.QRect(10, 50, 361, 192))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabelaAtributos.sizePolicy().hasHeightForWidth())
        self.tabelaAtributos.setSizePolicy(sizePolicy)
        self.tabelaAtributos.setMinimumSize(QtCore.QSize(0, 0))
        self.tabelaAtributos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabelaAtributos.setObjectName("tabelaAtributos")
        self.tabelaAtributos.setColumnCount(3)
        self.tabelaAtributos.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tabelaAtributos.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabelaAtributos.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabelaAtributos.setHorizontalHeaderItem(2, item)
        self.tabelaAtributos.horizontalHeader().setCascadingSectionResizes(True)
        self.tabelaAtributos.horizontalHeader().setDefaultSectionSize(47)
        self.tabelaAtributos.horizontalHeader().setHighlightSections(True)
        self.tabelaAtributos.horizontalHeader().setMinimumSectionSize(31)
        self.tabelaAtributos.horizontalHeader().setStretchLastSection(True)
        self.tabelaAtributos.verticalHeader().setVisible(False)
        self.removerButton = QtGui.QPushButton(self.groupBox_2)
        self.removerButton.setEnabled(False)
        self.removerButton.setGeometry(QtCore.QRect(120, 245, 131, 40))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.removerButton.setFont(font)
        self.removerButton.setObjectName("removerButton")
        self.groupBox = QtGui.QGroupBox(self.page_4)
        self.groupBox.setGeometry(QtCore.QRect(30, 70, 379, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 29, 354, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.nomeLabel = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.nomeLabel.setFont(font)
        self.nomeLabel.setObjectName("nomeLabel")
        self.gridLayout.addWidget(self.nomeLabel, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.instanciaLabel = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.instanciaLabel.setFont(font)
        self.instanciaLabel.setObjectName("instanciaLabel")
        self.gridLayout.addWidget(self.instanciaLabel, 1, 1, 1, 1)
        self.atributosLabel = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.atributosLabel.setFont(font)
        self.atributosLabel.setObjectName("atributosLabel")
        self.gridLayout.addWidget(self.atributosLabel, 0, 3, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.dadosButton.setText(QtGui.QApplication.translate("MainWindow", "Dados", None, QtGui.QApplication.UnicodeUTF8))
        self.classificacaoButton.setText(QtGui.QApplication.translate("MainWindow", "Classificação", None, QtGui.QApplication.UnicodeUTF8))
        self.entrada2Button.setText(QtGui.QApplication.translate("MainWindow", "Entrada 2", None, QtGui.QApplication.UnicodeUTF8))
        self.resultado2Button.setText(QtGui.QApplication.translate("MainWindow", "Resultado 2", None, QtGui.QApplication.UnicodeUTF8))
        self.abrirButton.setText(QtGui.QApplication.translate("MainWindow", "Abrir dataset...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Atributos", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelaAtributos.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "No.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelaAtributos.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Nome", None, QtGui.QApplication.UnicodeUTF8))
        self.removerButton.setText(QtGui.QApplication.translate("MainWindow", "Remover", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.nomeLabel.setText(QtGui.QApplication.translate("MainWindow", "Nenhum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Instâncias:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Atributos:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Nome:", None, QtGui.QApplication.UnicodeUTF8))
        self.instanciaLabel.setText(QtGui.QApplication.translate("MainWindow", "Nenhum", None, QtGui.QApplication.UnicodeUTF8))
        self.atributosLabel.setText(QtGui.QApplication.translate("MainWindow", "Nenhum", None, QtGui.QApplication.UnicodeUTF8))

